{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Pipeline evaluation"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "This notebook present how to evaluate a neural search pipeline using pairs of query and answers."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from cherche import data, rank, retrieve\n",
    "from sentence_transformers import SentenceTransformer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name '__file__' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/hs/7cm2nspd7qv45t5_pr9mv1580000gn/T/ipykernel_63348/234278809.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mSemanlinkRDF\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/var/folders/hs/7cm2nspd7qv45t5_pr9mv1580000gn/T/ipykernel_63348/4046707033.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     29\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 30\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdoc_g\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mload_doc_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     31\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtag_g\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mload_tag_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     32\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_ft_processor\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/var/folders/hs/7cm2nspd7qv45t5_pr9mv1580000gn/T/ipykernel_63348/4046707033.py\u001b[0m in \u001b[0;36mload_doc_graph\u001b[0;34m(g)\u001b[0m\n\u001b[1;32m    202\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    203\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mload_doc_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mg\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mrdflib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGraph\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m->\u001b[0m \u001b[0mrdflib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGraph\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 204\u001b[0;31m     \u001b[0mpath\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpathlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m__file__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparent\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjoinpath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"dump/sldocs.ttl\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    205\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0m_load_slfile_\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpath\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    206\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name '__file__' is not defined"
     ]
    }
   ],
   "source": [
    "SemanlinkRDF()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of urllib3.packages.six failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 287, in update_class\n",
      "    old_obj = getattr(old, key)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/urllib3/packages/six.py\", line 97, in __get__\n",
      "    setattr(obj, self.name, result)  # Invokes __set__.\n",
      "AttributeError: 'NoneType' object has no attribute 'cStringIO'\n",
      "]\n",
      "[autoreload of pandas._config.config failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    ref.__class__ = new\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/_config/config.py\", line 198, in __setattr__\n",
      "    raise OptionError(\"You can only set the value of existing options\")\n",
      "pandas._config.config.OptionError: 'You can only set the value of existing options'\n",
      "]\n",
      "[autoreload of pandas.core.missing failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _pad_1d() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.boolean failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.categorical failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: map() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.integer failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.floating failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.base failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: set_names() requires a code object with 5 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.numpy_ failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.period failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _format_native_types() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.string_ failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __eq__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.string_arrow failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: astype() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.arrays.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.extension failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.category failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _format_attrs() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.numeric failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __contains__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimelike failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __array_wrap__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.datetimes failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.multi failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/indexes/multi.py\", line 22, in <module>\n",
      "    from pandas._libs.hashtable import duplicated_int64\n",
      "ImportError: cannot import name 'duplicated_int64' from 'pandas._libs.hashtable' (/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/_libs/hashtable.cpython-38-darwin.so)\n",
      "]\n",
      "[autoreload of pandas.core.indexes.timedeltas failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 340, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__)),\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _simple_new() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.period failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _format_native_types() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.indexes.range failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _union() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of pandas.core.internals.blocks failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: reduce() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.reshape.concat failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: concat() requires a code object with 5 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.window.rolling failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/window/rolling.py\", line 54, in <module>\n",
      "    from pandas.core.groupby.base import GotItemMixin, ShallowMixin\n",
      "ImportError: cannot import name 'GotItemMixin' from 'pandas.core.groupby.base' (/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/groupby/base.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.ewm failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/window/ewm.py\", line 30, in <module>\n",
      "    from pandas.core.window.rolling import BaseWindow, BaseWindowGroupby, dispatch\n",
      "ImportError: cannot import name 'dispatch' from 'pandas.core.window.rolling' (/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/window/rolling.py)\n",
      "]\n",
      "[autoreload of pandas.core.window.expanding failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/window/expanding.py\", line 15, in <module>\n",
      "    class Expanding(RollingAndExpandingMixin):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/core/window/expanding.py\", line 141, in Expanding\n",
      "    @Appender(_shared_docs[\"count\"])\n",
      "KeyError: 'count'\n",
      "]\n",
      "[autoreload of pandas.core.series failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _check_is_chained_assignment_possible() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.core.frame failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _check_is_chained_assignment_possible() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of pandas.io.excel._base failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: read_excel() requires a code object with 5 free vars, not 4\n",
      "]\n",
      "[autoreload of pandas.io.html failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: read_html() requires a code object with 5 free vars, not 4\n",
      "]\n",
      "[autoreload of pandas.io.json._json failed: Traceback (most recent call last):\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/io/json/_json.py\", line 39, in <module>\n",
      "    from pandas.io.parsers import validate_integer\n",
      "ImportError: cannot import name 'validate_integer' from 'pandas.io.parsers' (/Users/raphaelsourty/opt/miniconda3/envs/cherche/lib/python3.8/site-packages/pandas/io/parsers/__init__.py)\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "import pathlib\n",
    "import typing as typing\n",
    "\n",
    "\n",
    "from flashtext import KeywordProcessor\n",
    "\n",
    "\n",
    "__all__ = [\"SemanlinkRDF\"]\n",
    "\n",
    "\n",
    "class SemanlinkRDF:\n",
    "    \"\"\"\"\"\"\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "7b170744ab9cf7446ed3e27cb2734f2273f9ffda6b52a7d603d13471f7231bb1"
  },
  "kernelspec": {
   "display_name": "Python 3.8.5 64-bit ('cherche': conda)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
